### ISSUE TITLE
Typo in findGroupByInit

### ISSUE THREAD

**Issue by cdoublev** [hrsh7th/react-inview-hook#1]
Hello,

I was playing with your hook and found a typo [there](https://github.com/hrsh7th/react-inview-hook/blob/master/src/cache.ts#L36). Each statement with `group.observerInit` should use `group.observer`, I think.

Thanks for sharing it. At least I hope that opening this issue may help someone who also want to have a look on it.

**Comment by hrsh7th** [comment]
Thanks for your report.

I checked it, currently implementation is not good but using `group.observerInit` is right, I thought.

Probably `IntersectionObserverInit` should normalize before call `findGroupByInit` (`normalize` is [here](https://github.com/hrsh7th/react-inview-hook/blob/master/src/group.ts#L71))
(Because, if `rootMargin` property was provided as `null`, It is same for `0px`. But currently implementation is not check it)

Oh... and I found bug, `group.observerInit.root` is wrong, should check `group.observerInit.root.current` instead it.

**Comment by hrsh7th** [comment]
I try to fix this in #2.
What do you think it?

**Comment by cdoublev** [comment]
Oh, I missed `public readonly observerInit: IntersectionObserverInit` in the `Group` constructor, when manually copy/pasting/processing TypeScript into JavaScript in a CodePen. This is where `group.observerInit` comes from, ok.

Quick note: `group.observerInit.root === group.observer.root`, as well as for `rootMargin` and `thresolds`. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root). 

I properly git cloned and builded your hook in a React app and it works fine.

**Comment by cdoublev** [comment]
In case you want to continue improving your hook, here is why I will try to create my own from scratch, ie. my requirements:
- use a unique callback for all observers (to ease caching observers)
- use a single (cached) observer for each unique set of given intersection options
- observe multiple targets with a single hook call
- observe the same target with multiple callbacks (observers)
- unobserve target when unmounted (or if it should intersect once)
- disconnect observer when it has no more target to observe

**Comment by hrsh7th** [comment]
> use a unique callback for all observers (to ease caching observers)
It's sounds good. But I wouldn't implement this maybe (I think, currently implementation is simple rather than it).

> use a single (cached) observer for each unique set of given intersection options
It is implemented.

> observe multiple targets with a single hook call
It's sounds good. This is easy to implement.

> observe the same target with multiple callbacks (observers)
It is possible in currently implementation, I thought.

> unobserve target when unmounted (or if it should intersect once)
It is implemented. You can use `unobserveOnEnter`.

> disconnect observer when it has no more target to observe
It is implemented that's `index.ts`'s `cache.remove`.

You can open PR.
Or feel free to create your one, thanks.
